import type { MediaAssetKind } from "@/core/entities/media-asset";
import type { ToolDescriptor } from "@/core/tool-registry/ToolDescriptor";
import type { ToolCommand } from "@/core/tool-registry/ToolCommand";
import type { ToolExecutionContext } from "@/core/tool-registry/ToolExecutionContext";
import type { UserFileRepository } from "@/core/use-cases/UserFileRepository";
import type { BlogAssetRepository } from "@/core/use-cases/BlogAssetRepository";
import {
  projectUserFileToConversationMediaAssetCandidate,
  type ConversationMediaAssetCandidate,
} from "@/lib/media/media-asset-projection";

const ALLOWED_MEDIA_ASSET_KINDS = [
  "audio",
  "chart",
  "graph",
  "image",
  "video",
  "subtitle",
  "waveform",
] as const satisfies readonly MediaAssetKind[];

export interface ListConversationMediaAssetsInput {
  kinds?: MediaAssetKind[];
  limit?: number;
}

interface ListConversationMediaAssetsOutput {
  ok: true;
  action: "list_conversation_media_assets";
  conversationId: string;
  assets: ConversationMediaAssetCandidate[];
  summary: string;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function isAllowedMediaAssetKind(value: string): value is MediaAssetKind {
  return ALLOWED_MEDIA_ASSET_KINDS.includes(value as MediaAssetKind);
}

export function parseListConversationMediaAssetsInput(value: unknown): ListConversationMediaAssetsInput {
  if (!isRecord(value)) {
    return {};
  }

  const kinds = Array.isArray(value.kinds)
    ? value.kinds.map((item) => {
        if (typeof item !== "string" || !isAllowedMediaAssetKind(item)) {
          throw new Error(`Unsupported media asset kind: ${String(item)}`);
        }

        return item;
      })
    : undefined;

  const limit = value.limit;
  if (limit !== undefined && (typeof limit !== "number" || !Number.isFinite(limit))) {
    throw new Error("limit must be a finite number when provided.");
  }

  return {
    ...(kinds ? { kinds } : {}),
    ...(typeof limit === "number" ? { limit } : {}),
  };
}

/**
 * Projects a BlogAsset (hero image stored in blog_assets table with a blogasset_ ID)
 * into the same ConversationMediaAssetCandidate shape used for user file assets.
 * This makes blogasset_ IDs discoverable via list_conversation_media_assets so the
 * LLM doesn't have to recall them verbatim from conversation history.
 */
function projectBlogAssetToMediaCandidate(
  blogAsset: {
    id: string;
    kind: string;
    mimeType: string;
    altText: string;
    width: number | null;
    height: number | null;
    createdAt: string;
    createdByUserId: string;
  },
): ConversationMediaAssetCandidate | null {
  // Only surface image assets from the blog_assets table into compose_media context
  if (!blogAsset.mimeType.startsWith("image/")) {
    return null;
  }

  return {
    assetId: blogAsset.id,
    assetKind: "image",
    label: blogAsset.altText || blogAsset.id,
    fileName: blogAsset.id,
    mimeType: blogAsset.mimeType,
    source: "generated",
    retentionClass: "durable",
    createdAt: blogAsset.createdAt,
    conversationId: null,
    derivativeOfAssetId: null,
    toolName: "generate_blog_image",
    ...(typeof blogAsset.width === "number" ? { width: blogAsset.width } : {}),
    ...(typeof blogAsset.height === "number" ? { height: blogAsset.height } : {}),
  };
}

class ListConversationMediaAssetsCommand implements ToolCommand<
  ListConversationMediaAssetsInput,
  ListConversationMediaAssetsOutput
> {
  constructor(
    private readonly userFileRepository: UserFileRepository,
    private readonly blogAssetRepository?: BlogAssetRepository,
  ) {}

  async execute(
    input: ListConversationMediaAssetsInput,
    context?: ToolExecutionContext,
  ): Promise<ListConversationMediaAssetsOutput> {
    if (!context || context.role === "ANONYMOUS") {
      throw new Error("Sign in is required to inspect reusable media assets.");
    }

    if (!context.conversationId) {
      throw new Error("Conversation context is required to list reusable media assets.");
    }

    const limit = Math.min(Math.max(Math.trunc(input.limit ?? 25), 1), 25);
    const allowedKinds = new Set(input.kinds ?? ALLOWED_MEDIA_ASSET_KINDS);

    // 1. User file assets (uf_* IDs: audio, chart, graph, video, image uploads, etc.)
    const files = await this.userFileRepository.listByConversation(context.conversationId);
    const userFileAssets = files
      .filter((file) => file.userId === context.userId)
      .map(projectUserFileToConversationMediaAssetCandidate)
      .filter((asset): asset is ConversationMediaAssetCandidate => Boolean(asset))
      .filter((asset) => allowedKinds.has(asset.assetKind));

    // 2. Blog image assets (blogasset_* IDs from blog_assets table).
    //    These are generated by generate_blog_image and stored separately from user files.
    //    They are discoverable here so the LLM doesn't have to recall full UUIDs from history.
    const blogImageAssets: ConversationMediaAssetCandidate[] = [];
    if (allowedKinds.has("image") && this.blogAssetRepository && context.userId) {
      const blogAssets = await this.blogAssetRepository.listByUser(context.userId, {
        limit: 25,
        kinds: ["hero"],
      });
      for (const blogAsset of blogAssets) {
        const candidate = projectBlogAssetToMediaCandidate(blogAsset);
        if (candidate) {
          blogImageAssets.push(candidate);
        }
      }
    }

    // Merge, deduplicate by assetId, sort newest first, apply limit
    const seen = new Set<string>();
    const merged: ConversationMediaAssetCandidate[] = [];
    for (const asset of [...userFileAssets, ...blogImageAssets]) {
      if (!seen.has(asset.assetId)) {
        seen.add(asset.assetId);
        merged.push(asset);
      }
    }
    const assets = merged
      .sort((left, right) => right.createdAt.localeCompare(left.createdAt))
      .slice(0, limit);

    return {
      ok: true,
      action: "list_conversation_media_assets",
      conversationId: context.conversationId,
      assets,
      summary: assets.length === 0
        ? "No reusable media assets were found for this conversation."
        : `Returned ${assets.length} reusable media asset${assets.length === 1 ? "" : "s"} for this conversation. Use the assetId values exactly as shown when referencing them in compose_media clips. Charts and graphs are valid direct governed inputs; if a derived image exists, preserve the original source via sourceAssetId.`,
    };
  }
}

export function createListConversationMediaAssetsTool(
  userFileRepository: UserFileRepository,
  blogAssetRepository?: BlogAssetRepository,
): ToolDescriptor<ListConversationMediaAssetsInput, ListConversationMediaAssetsOutput> {
  return {
    name: "list_conversation_media_assets",
    schema: {
      description:
        "List reusable governed media assets already attached to the current conversation, including blog images (blogasset_ IDs). "
        + "ALWAYS call this before compose_media when the user wants to reuse a previously generated chart, graph, audio file, image, or video. "
        + "The assetId values returned are the exact canonical IDs to pass into compose_media clips — copy them verbatim.",
      input_schema: {
        type: "object",
        properties: {
          kinds: {
            type: "array",
            description: "Optional media kinds to include in the result.",
            items: {
              type: "string",
              enum: [...ALLOWED_MEDIA_ASSET_KINDS],
            },
          },
          limit: {
            type: "number",
            description: "Maximum number of assets to return, between 1 and 25.",
          },
        },
      },
    },
    command: new ListConversationMediaAssetsCommand(userFileRepository, blogAssetRepository),
    roles: ["AUTHENTICATED", "APPRENTICE", "STAFF", "ADMIN"],
    category: "content",
  };
}