import { z } from "zod";
import type { MediaCompositionClip, MediaCompositionPlan } from "@/core/entities/media-composition";
import {
  DEFAULT_MEDIA_COMPOSITION_PROFILE,
  MEDIA_COMPOSITION_PROFILE_IDS,
  STANDARD_MEDIA_COMPOSITION_RESOLUTION,
  getDefaultResolutionForPlan,
  resolveMediaCompositionProfile,
} from "./media-composition-profile";

export const DEFAULT_MEDIA_COMPOSITION_RESOLUTION = {
  ...STANDARD_MEDIA_COMPOSITION_RESOLUTION,
} as const;

export const MediaCompositionClipSchema = z.object({
  assetId: z.string().min(1),
  kind: z.enum(["image", "video", "audio", "chart", "graph"]),
  sourceAssetId: z.string().min(1).optional(),
  startTime: z.number().nonnegative().optional(),
  duration: z.number().positive().optional(),
});

export const MediaCompositionPlanSchema = z.object({
  id: z.string().min(1),
  conversationId: z.string().min(1),
  mode: z.literal("browser_short_explainer").optional(),
  visualClips: z.array(MediaCompositionClipSchema).max(5),
  audioClips: z.array(MediaCompositionClipSchema).max(5),
  profile: z.enum(MEDIA_COMPOSITION_PROFILE_IDS).default(DEFAULT_MEDIA_COMPOSITION_PROFILE),
  defaults: z.object({
    durationTargetSeconds: z.number().positive().optional(),
  }).optional(),
  overrides: z.object({
    title: z.string().min(1).optional(),
    hookText: z.string().min(1).optional(),
    closingText: z.string().min(1).optional(),
  }).optional(),
  subtitlePolicy: z.enum(["none", "burned", "sidecar", "both"]).default("none"),
  waveformPolicy: z.enum(["none", "generate"]).default("none"),
  outputFormat: z.enum(["mp4", "webm"]).default("mp4"),
  resolution: z
    .object({
      width: z.number().positive(),
      height: z.number().positive(),
    })
    .optional(),
});

export function normalizeMediaCompositionPlan(raw: unknown, overrideConversationId?: string): MediaCompositionPlan | null {
  const result = MediaCompositionPlanSchema.safeParse(raw);
  if (!result.success) return null;
  const plan = result.data as MediaCompositionPlan;

  return {
    ...plan,
    conversationId: overrideConversationId ?? plan.conversationId,
    resolution: plan.resolution ?? getDefaultResolutionForPlan(plan),
  };
}

export function validatePlanConstraints(plan: MediaCompositionPlan): string | null {
  if (plan.visualClips.length === 0 && plan.audioClips.length === 0) {
    return "Plan must contain at least one visual or audio clip.";
  }

  if (plan.audioClips.some((clip) => clip.kind !== "audio")) {
    return "Audio clips must be audio assets.";
  }

  const resolvedProfile = resolveMediaCompositionProfile(plan);

  if (resolvedProfile === "still_image_narration_fast") {
    if (
      plan.visualClips.length !== 1
      || plan.visualClips.some((clip) => clip.kind !== "image" && clip.kind !== "chart" && clip.kind !== "graph")
    ) {
      return "The still_image_narration_fast profile requires exactly one image-compatible visual clip.";
    }

    if (plan.audioClips.length > 1) {
      return "The still_image_narration_fast profile supports at most one narration audio clip.";
    }
  }

  // Prevent impossible states
  if (plan.visualClips.length === 0 && plan.subtitlePolicy === "burned") {
    return "Cannot burn subtitles into audio-only output.";
  }

  if (plan.resolution && (plan.resolution.width % 2 !== 0 || plan.resolution.height % 2 !== 0)) {
    return "Resolution width and height must be even numbers.";
  }

  return null;
}

export function validateExecutablePlanConstraints(plan: MediaCompositionPlan): string | null {
  const structuralError = validatePlanConstraints(plan);
  if (structuralError) {
    return structuralError;
  }

  if (plan.visualClips.some((clip) => clip.kind !== "image" && clip.kind !== "video")) {
    return "Visual clips must be image or video assets. Charts and graphs must be rendered to an image before video composition.";
  }

  return null;
}

export type MediaCompositionAssetIdentityKind = MediaCompositionClip["kind"];

export interface MediaCompositionAssetIdentityCandidate {
  assetId: string;
  kind: MediaCompositionAssetIdentityKind;
  aliases?: string[];
  derivativeOfAssetId?: string | null;
}

export interface CanonicalizeMediaCompositionPlanOptions {
  assetCandidates?: readonly MediaCompositionAssetIdentityCandidate[];
  aliasBindings?: Record<string, string>;
}

export interface AssetReferenceRepair {
  reference: string;
  resolvedAssetId: string;
  strategy: "alias_binding" | "candidate_alias";
}

// uf_ and asset_ accept any alphanumeric suffix.
// blogasset_ must have a full UUID suffix (generated by randomUUID()) to catch LLM-truncated IDs early.
const CANONICAL_MEDIA_COMPOSITION_ASSET_ID_PATTERN =
  /^(uf_[a-z0-9_-]+|asset_[a-z0-9_-]+|chart_[a-z0-9_-]+|graph_[a-z0-9_-]+|blogasset_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$/i;

export function isCanonicalMediaCompositionAssetId(value: string | null | undefined): boolean {
  const trimmed = value?.trim();
  if (!trimmed) {
    return false;
  }

  return CANONICAL_MEDIA_COMPOSITION_ASSET_ID_PATTERN.test(trimmed);
}

export function validateMediaCompositionAssetReferences(plan: MediaCompositionPlan): string | null {
  for (const [index, clip] of plan.visualClips.entries()) {
    if (!isCanonicalMediaCompositionAssetId(clip.assetId)) {
      const isBlogAsset = clip.assetId.startsWith("blogasset_");
      const hint = isBlogAsset
        ? "blogasset_ IDs must include the full UUID — copy the complete ID exactly as returned by the tool."
        : "Use IDs from prior tool results (uf_, asset_, or blogasset_<full-UUID>). Never use job_ IDs or shortened fragments.";
      return `Invalid visual clip assetId at index ${index}: "${clip.assetId}". ${hint}`;
    }
  }

  for (const [index, clip] of plan.audioClips.entries()) {
    if (!isCanonicalMediaCompositionAssetId(clip.assetId)) {
      const isBlogAsset = clip.assetId.startsWith("blogasset_");
      const hint = isBlogAsset
        ? "blogasset_ IDs must include the full UUID — copy the complete ID exactly as returned by the tool."
        : "Use IDs from prior tool results (uf_, asset_, or blogasset_<full-UUID>). Never use job_ IDs or shortened fragments.";
      return `Invalid audio clip assetId at index ${index}: "${clip.assetId}". ${hint}`;
    }
  }

  return null;
}


export class InvalidMediaCompositionPlanAssetReferenceError extends Error {
  constructor(reference: string) {
    super(`Unknown media composition asset reference: ${reference}`);
    this.name = "InvalidMediaCompositionPlanAssetReferenceError";
  }
}

function trimReference(value: string): string {
  return value.trim();
}

function normalizeAlias(value: string): string {
  return trimReference(value).toLowerCase().replace(/[^a-z0-9]/g, "");
}

function isCandidateCompatibleWithClip(
  candidateKind: MediaCompositionAssetIdentityKind,
  clipKind: MediaCompositionClip["kind"],
): boolean {
  return candidateKind === clipKind;
}

function buildCandidateAliasIndex(
  candidates: readonly MediaCompositionAssetIdentityCandidate[],
): Map<string, Map<MediaCompositionAssetIdentityKind, string>> {
  const index = new Map<string, Map<MediaCompositionAssetIdentityKind, string>>();

  const setAlias = (alias: string, candidate: MediaCompositionAssetIdentityCandidate) => {
    const existing = index.get(alias) ?? new Map<MediaCompositionAssetIdentityKind, string>();
    if (!existing.has(candidate.kind)) {
      existing.set(candidate.kind, candidate.assetId);
    }
    index.set(alias, existing);
  };

  for (const candidate of candidates) {
    const normalizedAssetId = normalizeAlias(candidate.assetId);
    if (normalizedAssetId) {
      setAlias(normalizedAssetId, candidate);
    }

    for (const alias of candidate.aliases ?? []) {
      const normalized = normalizeAlias(alias);
      if (!normalized) {
        continue;
      }

      setAlias(normalized, candidate);
    }
  }

  return index;
}

export function canonicalizeMediaCompositionPlanWithRepairs(
  plan: MediaCompositionPlan,
  options: CanonicalizeMediaCompositionPlanOptions = {},
): { plan: MediaCompositionPlan; repairs: AssetReferenceRepair[] } {
  const aliasBindings = new Map<string, string>(
    Object.entries(options.aliasBindings ?? {}).map(([alias, assetId]) => [normalizeAlias(alias), assetId]),
  );
  const candidateKindByAssetId = new Map<string, MediaCompositionAssetIdentityKind>(
    (options.assetCandidates ?? []).map((candidate) => [candidate.assetId, candidate.kind]),
  );
  const candidateAliasIndex = buildCandidateAliasIndex(options.assetCandidates ?? []);
  const repairs: AssetReferenceRepair[] = [];

  const canonicalizeClip = (clip: MediaCompositionClip): MediaCompositionClip => {
    const reference = trimReference(clip.assetId);
    const normalized = normalizeAlias(reference);

    const aliasBoundAssetId = aliasBindings.get(normalized);
    const aliasBoundKind = aliasBoundAssetId ? candidateKindByAssetId.get(aliasBoundAssetId) : null;
    if (
      aliasBoundAssetId
      && aliasBoundAssetId !== clip.assetId
      && (!aliasBoundKind || isCandidateCompatibleWithClip(aliasBoundKind, clip.kind))
    ) {
      repairs.push({
        reference: clip.assetId,
        resolvedAssetId: aliasBoundAssetId,
        strategy: "alias_binding",
      });
      return { ...clip, assetId: aliasBoundAssetId };
    }

    const candidateAssetId = candidateAliasIndex.get(normalized)?.get(clip.kind);
    if (candidateAssetId && candidateAssetId !== clip.assetId) {
      repairs.push({
        reference: clip.assetId,
        resolvedAssetId: candidateAssetId,
        strategy: "candidate_alias",
      });
      return { ...clip, assetId: candidateAssetId };
    }

    const knownAlias = candidateAliasIndex.has(normalized) || aliasBindings.has(normalized);
    if (!knownAlias && !isCanonicalMediaCompositionAssetId(reference)) {
      throw new InvalidMediaCompositionPlanAssetReferenceError(clip.assetId);
    }

    return clip;
  };

  return {
    plan: {
      ...plan,
      visualClips: plan.visualClips.map(canonicalizeClip),
      audioClips: plan.audioClips.map(canonicalizeClip),
    },
    repairs,
  };
}
