import type { RoleName } from "@/core/entities/user";

const SHARED_MEMBER_TOOL_SET = [
  "adjust_ui",
  "calculator",
  "compose_media",
  "generate_chart",
  "generate_graph",
  "get_checklist",
  "get_corpus_summary",
  "get_current_page",
  "get_my_affiliate_summary",
  "get_my_job_status",
  "get_my_profile",
  "get_my_referral_qr",
  "get_section",
  "inspect_runtime_context",
  "inspect_theme",
  "list_available_pages",
  "list_conversation_media_assets",
  "list_my_jobs",
  "list_my_referral_activity",
  "list_practitioners",
  "navigate_to_page",
  "search_corpus",
  "search_my_conversations",
  "search_relationship_memory",
  "set_preference",
  "set_theme",
  "update_my_profile",
];

const STAFF_TOOL_SET = [
  ...SHARED_MEMBER_TOOL_SET.slice(0, SHARED_MEMBER_TOOL_SET.indexOf("search_corpus")),
  "produce_product",
  ...SHARED_MEMBER_TOOL_SET.slice(SHARED_MEMBER_TOOL_SET.indexOf("search_corpus")),
];

export const EXPECTED_ROLE_TOOL_SETS: Record<RoleName, string[]> = {
  ANONYMOUS: [
    "adjust_ui",
    "calculator",
    "generate_chart",
    "generate_graph",
    "get_checklist",
    "get_corpus_summary",
    "get_current_page",
    "get_section",
    "inspect_runtime_context",
    "inspect_theme",
    "list_available_pages",
    "list_practitioners",
    "navigate_to_page",
    "search_corpus",
    "set_theme",
  ],
  AUTHENTICATED: [...SHARED_MEMBER_TOOL_SET],
  APPRENTICE: [...SHARED_MEMBER_TOOL_SET],
  STAFF: STAFF_TOOL_SET,
  ADMIN: [
    "adjust_ui",
    "admin_prioritize_leads",
    "admin_prioritize_offer",
    "admin_search",
    "admin_triage_routing_risk",
    "approve_journal_post",
    "calculator",
    "cancel_appliance_restore",
    "compose_blog_article",
    "compose_media",
    "configure_backup_policy",
    "configure_tool_availability",
    "confirm_appliance_restore",
    "create_appliance_backup",
    "draft_content",
    "execute_appliance_restore",
    "generate_blog_image_prompt",
    "generate_chart",
    "generate_graph",
    "get_admin_affiliate_summary",
    "get_checklist",
    "get_corpus_summary",
    "get_current_page",
    "get_deferred_job_status",
    "get_journal_post",
    "get_journal_workflow_summary",
    "get_my_affiliate_summary",
    "get_my_job_status",
    "get_my_profile",
    "get_my_referral_qr",
    "get_section",
    "inspect_runtime_context",
    "inspect_runtime_logs",
    "inspect_theme",
    "list_admin_referral_exceptions",
    "list_appliance_backups",
    "list_available_pages",
    "list_conversation_media_assets",
    "list_deferred_jobs",
    "list_journal_posts",
    "list_journal_revisions",
    "list_my_jobs",
    "list_my_referral_activity",
    "list_practitioners",
    "navigate_to_page",
    "prepare_appliance_restore",
    "prepare_journal_post_for_publish",
    "produce_blog_article",
    "produce_product",
    "publish_content",
    "publish_journal_post",
    "qa_blog_article",
    "request_pre_restore_backup",
    "resolve_blog_article_qa",
    "restore_journal_revision",
    "search_corpus",
    "search_my_conversations",
    "search_relationship_memory",
    "select_journal_hero_image",
    "set_preference",
    "set_theme",
    "submit_journal_review",
    "update_journal_draft",
    "update_journal_metadata",
    "update_my_profile",
    "validate_appliance_backup",
  ],
};
